/* ==========================================================================
   Hamleys Global Count Dashboard — app.js
   Core data engine: load JSON, normalize, filter, aggregate, render UI.
   No backend — reads data/gc-data.json (regenerated by admin.html).
   ========================================================================== */

'use strict';

/* ---------------------------------------------------------------------- *
 * 1. GLOBAL STATE
 * ---------------------------------------------------------------------- */
const APP = {
  columns: [],          // raw column headers from gc-data.json
  rows: [],             // raw row arrays (dynamic, unmodified)
  storeMaster: [],      // [{code,name,rm,rom,sd}]
  storeMasterByCode: {},// code -> mapping entry
  meta: {},
  records: [],          // normalized records built from rows + mapping
  filtered: [],         // records after filters applied
  colIdx: {},           // column-name -> index map (resolved dynamically)
  storePage: 1,
  storePageSize: 15,
  storeSort: { key: 'date', dir: 'desc' },
  rawPage: 1,
  rawPageSize: 15,
  rawSort: { key: null, dir: 'asc' },
  rawFilteredRows: [],
  storeExportData: [],
};

/* ---------------------------------------------------------------------- *
 * 2. UTILITIES
 * ---------------------------------------------------------------------- */
function $(sel, ctx) { return (ctx || document).querySelector(sel); }
function $all(sel, ctx) { return Array.from((ctx || document).querySelectorAll(sel)); }

function debounce(fn, wait) {
  let t;
  return function (...args) { clearTimeout(t); t = setTimeout(() => fn.apply(this, args), wait); };
}

function fmtNum(n, decimals) {
  if (n === null || n === undefined || isNaN(n)) return '—';
  return Number(n).toLocaleString('en-IN', { maximumFractionDigits: decimals ?? 0, minimumFractionDigits: decimals ?? 0 });
}

function fmtPct(n) { return (isNaN(n) ? '0' : String(Math.round(Number(n)))) + '%'; }

/**
 * Parse a value (Date, Excel serial number, or "YYYY-MM-DD"/free-text string)
 * into a *normalized calendar-day* Date pinned at UTC noon.
 *
 * Each input kind needs its own read, because they carry their literal
 * calendar values differently:
 *  - A `Date` here would come from SheetJS's cellDates:true, which builds it
 *    via the LOCAL Date constructor from the literal Y/M/D/H/M/S it decoded
 *    out of the Excel serial. LOCAL getters (not UTC) recover those literal
 *    values, regardless of what timezone the browser/OS happens to be set
 *    to. (A previous version of this function applied a blanket "+12 hours,
 *    then read UTC fields" shift, which corrupted every afternoon/evening
 *    entry — the vast majority of real submissions — by rolling them to the
 *    next calendar day under IST.)
 *  - A raw number is a leftover Excel serial: literal epoch-day math gives a
 *    UTC instant whose UTC fields are already the literal values, no
 *    timezone dependency.
 *  - An "YYYY-MM-DD" string (what gc-data.json actually stores) is parsed
 *    directly, no Date-object detour at all.
 */
function parseAnyDate(v) {
  if (!v && v !== 0) return null;
  let y, m, day;
  if (v instanceof Date) {
    y = v.getFullYear(); m = v.getMonth(); day = v.getDate();
  } else if (typeof v === 'number') {
    const raw = new Date(Math.round((v - 25569) * 86400 * 1000));
    y = raw.getUTCFullYear(); m = raw.getUTCMonth(); day = raw.getUTCDate();
  } else {
    const s = String(v).trim();
    const iso = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (iso) {
      y = Number(iso[1]); m = Number(iso[2]) - 1; day = Number(iso[3]);
    } else {
      const raw = new Date(s);
      if (!raw || isNaN(raw.getTime())) return null;
      y = raw.getFullYear(); m = raw.getMonth(); day = raw.getDate();
    }
  }
  return new Date(Date.UTC(y, m, day, 12, 0, 0));
}

function fmtDate(d) {
  if (!d) return '—';
  const dt = (d instanceof Date) ? d : parseAnyDate(d);
  if (!dt) return '—';
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' });
}

/** Format a normalized Date as "YYYY-MM-DD" using UTC fields — safe because
 *  parseAnyDate() always pins the instant at UTC noon of the correct day. */
function toLocalISODate(d) {
  if (!d) return '';
  const dt = (d instanceof Date) ? d : parseAnyDate(d);
  if (!dt) return '';
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, '0');
  const day = String(dt.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function monthLabel(d) {
  if (!d) return '—';
  return d.toLocaleDateString('en-GB', { month: 'short', year: 'numeric', timeZone: 'UTC' });
}

/** Indian Financial Year label (April–March), e.g. 15-Jun-2026 -> "FY 2026-27",
 *  10-Feb-2026 -> "FY 2025-26". Uses UTC fields to match parseAnyDate's anchoring. */
function fyLabel(d) {
  if (!d) return null;
  const y = d.getUTCFullYear();
  const m = d.getUTCMonth(); // 0 = Jan ... 3 = Apr
  const startYear = m >= 3 ? y : y - 1;
  const endYearShort = String((startYear + 1) % 100).padStart(2, '0');
  return `FY ${startYear}-${endYearShort}`;
}

/** Find a column index by fuzzy (case-insensitive, substring) name match */
function findColIndex(columns, candidates) {
  const lower = columns.map(c => (c || '').toString().toLowerCase().trim());
  for (const cand of candidates) {
    const idx = lower.findIndex(c => c === cand.toLowerCase());
    if (idx !== -1) return idx;
  }
  for (const cand of candidates) {
    const idx = lower.findIndex(c => c.includes(cand.toLowerCase()));
    if (idx !== -1) return idx;
  }
  return -1;
}

function animateCounter(el, target, isDecimal, suffix) {
  const start = 0;
  const duration = 900;
  const startTime = performance.now();
  function tick(now) {
    const p = Math.min(1, (now - startTime) / duration);
    const eased = 1 - Math.pow(1 - p, 3);
    const val = start + (target - start) * eased;
    el.textContent = (isDecimal ? val.toFixed(1) : Math.round(val).toLocaleString('en-IN')) + (suffix || '');
    if (p < 1) requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);
}

function groupBy(arr, keyFn) {
  const map = new Map();
  for (const item of arr) {
    const k = keyFn(item) || 'Unassigned';
    if (!map.has(k)) map.set(k, []);
    map.get(k).push(item);
  }
  return map;
}

function downloadFile(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}

/* ---------------------------------------------------------------------- *
 * 3. DATA LOADING
 * ---------------------------------------------------------------------- */
async function loadData(bustCache) {
  const url = 'data/gc-data.json' + (bustCache ? ('?t=' + Date.now()) : '');
  const res = await fetch(url);
  if (!res.ok) throw new Error('Could not load data/gc-data.json (HTTP ' + res.status + ')');
  const json = await res.json();

  APP.columns = json.columns || [];
  APP.rows = json.rows || [];
  APP.storeMaster = json.storeMaster || [];
  APP.meta = json.meta || {};
  APP.storeMasterByCode = {};
  APP.storeMaster.forEach(m => { APP.storeMasterByCode[m.code] = m; });

  resolveColumnIndexes();
  buildRecords();
  populateFilterOptions();
  applyFilters();

  $('#lastUpdatedText').textContent = APP.meta.lastUpdated || '—';
  $('#storeCountSub').textContent = `${APP.storeMaster.length} Stores Mapped · India Retail Operations`;
  document.getElementById('footerYear').textContent = new Date().getFullYear();
}

function resolveColumnIndexes() {
  const c = APP.columns;
  APP.colIdx = {
    storeCode: findColIndex(c, ['store code']),
    storeName: findColIndex(c, ['store name']),
    rm: findColIndex(c, ['rm']),
    rom: findColIndex(c, ['rom']),
    sd: findColIndex(c, ['sd']),
    date: findColIndex(c, ['date of global count', 'date']),
    gc: findColIndex(c, ["no. of sku's counted", 'no of skus counted', 'sku', 'global count']),
    shortageQty: findColIndex(c, ['shortage qty']),
    shortageMapValue: findColIndex(c, ['shortage map value']),
    excessQty: findColIndex(c, ['excess qty']),
    excessMapValue: findColIndex(c, ['excess map value']),
    netQtyDiff: findColIndex(c, ['total net qty difference', 'net qty difference']),
    netValueDiff: findColIndex(c, ['total net map value difference', 'net map value difference']),
    doneBy: findColIndex(c, ['global count done by', 'done by']),
    validatedBy: findColIndex(c, ['global count validated by', 'validated by']),
    movedTo2997: findColIndex(c, ['shortage qty moved to 2997', 'moved to 2997']),
    reason: findColIndex(c, ['reason for short or excess qty', 'reason']),
  };
}

/** Build normalized record objects from dynamic rows, filling gaps via storeMaster mapping */
function buildRecords() {
  const idx = APP.colIdx;
  APP.records = APP.rows.map((row, i) => {
    const storeCode = idx.storeCode !== -1 ? String(row[idx.storeCode] ?? '').trim() : '';
    const mapping = APP.storeMasterByCode[storeCode];

    let storeName = idx.storeName !== -1 ? row[idx.storeName] : (mapping ? mapping.name : '');
    let rm = idx.rm !== -1 ? row[idx.rm] : '';
    let rom = idx.rom !== -1 ? row[idx.rom] : '';
    let sd = idx.sd !== -1 ? row[idx.sd] : '';

    // Fill missing RM/ROM/SD from master mapping when blank
    if ((!rm || String(rm).trim() === '') && mapping) rm = mapping.rm;
    if ((!rom || String(rom).trim() === '') && mapping) rom = mapping.rom;
    if ((!sd || String(sd).trim() === '') && mapping) sd = mapping.sd;
    if ((!storeName || String(storeName).trim() === '') && mapping) storeName = mapping.name;

    const dateVal = idx.date !== -1 ? parseAnyDate(row[idx.date]) : null;
    const gc = idx.gc !== -1 ? Number(row[idx.gc]) || 0 : 0;

    return {
      _rowIndex: i,
      storeCode,
      storeName: storeName || storeCode || 'Unknown',
      rm: (rm || 'Unassigned').toString().trim(),
      rom: (rom || 'Unassigned').toString().trim(),
      sd: (sd || 'Unassigned').toString().trim(),
      date: dateVal,
      dateStr: dateVal ? toLocalISODate(dateVal) : '',
      month: dateVal ? monthLabel(dateVal) : 'Unknown',
      year: dateVal ? dateVal.getUTCFullYear() : null,
      fy: dateVal ? fyLabel(dateVal) : 'Unknown',
      gc,
      shortageQty: idx.shortageQty !== -1 ? Number(row[idx.shortageQty]) || 0 : 0,
      shortageMapValue: idx.shortageMapValue !== -1 ? Number(row[idx.shortageMapValue]) || 0 : 0,
      excessQty: idx.excessQty !== -1 ? Number(row[idx.excessQty]) || 0 : 0,
      excessMapValue: idx.excessMapValue !== -1 ? Number(row[idx.excessMapValue]) || 0 : 0,
      netQtyDiff: idx.netQtyDiff !== -1 ? Number(row[idx.netQtyDiff]) || 0 : 0,
      netValueDiff: idx.netValueDiff !== -1 ? Number(row[idx.netValueDiff]) || 0 : 0,
      doneBy: idx.doneBy !== -1 ? row[idx.doneBy] : '',
      validatedBy: idx.validatedBy !== -1 ? row[idx.validatedBy] : '',
      movedTo2997: idx.movedTo2997 !== -1 ? row[idx.movedTo2997] : '',
      reason: idx.reason !== -1 ? row[idx.reason] : '',
    };
  });
}

/* ---------------------------------------------------------------------- *
 * 4. FILTERS
 * ---------------------------------------------------------------------- */
function uniqueSorted(arr) {
  return Array.from(new Set(arr.filter(v => v !== null && v !== undefined && v !== ''))).sort((a, b) => String(a).localeCompare(String(b)));
}

function populateFilterOptions() {
  const dates = uniqueSorted(APP.records.map(r => r.dateStr)).sort();
  const months = uniqueSorted(APP.records.map(r => r.month));
  const fys = uniqueSorted(APP.records.map(r => r.fy)).filter(v => v !== 'Unknown');
  const rms = uniqueSorted(APP.records.map(r => r.rm));
  const roms = uniqueSorted(APP.records.map(r => r.rom));
  const sds = uniqueSorted(APP.records.map(r => r.sd));

  // Date From / Date To are native calendar pickers (<input type="date">),
  // not dropdowns — just bind their min/max to the range actually present
  // in the data so users can't pick out-of-range dates.
  const dateFromInput = $('#fDateFrom');
  const dateToInput = $('#fDateTo');
  if (dates.length) {
    if (dateFromInput) { dateFromInput.min = dates[0]; dateFromInput.max = dates[dates.length - 1]; }
    if (dateToInput) { dateToInput.min = dates[0]; dateToInput.max = dates[dates.length - 1]; }
  }

  fillSelect('#fMonth', months);
  fillSelect('#fYear', fys);
  fillSelect('#fRM', rms);
  fillSelect('#fROM', roms);
  fillSelect('#fSD', sds);
}

function fillSelect(sel, values, labelFn) {
  const el = $(sel);
  const current = el.value;
  const firstOption = el.querySelector('option');
  el.innerHTML = '';
  el.appendChild(firstOption);
  values.forEach(v => {
    const opt = document.createElement('option');
    opt.value = v;
    opt.textContent = labelFn ? labelFn(v) : v;
    el.appendChild(opt);
  });
  if (values.includes(current)) el.value = current;
}

function getFilterState() {
  return {
    dateFrom: $('#fDateFrom').value,
    dateTo: $('#fDateTo').value,
    month: $('#fMonth').value,
    fy: $('#fYear').value,
    rm: $('#fRM').value,
    rom: $('#fROM').value,
    sd: $('#fSD').value,
    search: $('#fSearch').value.trim().toLowerCase(),
  };
}

function applyFilters() {
  const f = getFilterState();
  APP.filtered = APP.records.filter(r => {
    if (f.dateFrom && r.dateStr && r.dateStr < f.dateFrom) return false;
    if (f.dateTo && r.dateStr && r.dateStr > f.dateTo) return false;
    if (f.month && r.month !== f.month) return false;
    if (f.fy && r.fy !== f.fy) return false;
    if (f.rm && r.rm !== f.rm) return false;
    if (f.rom && r.rom !== f.rom) return false;
    if (f.sd && r.sd !== f.sd) return false;
    if (f.search && !(`${r.storeCode} ${r.storeName}`.toLowerCase().includes(f.search))) return false;
    return true;
  });
  APP.storePage = 1;
  renderAll();
}

function resetFilters() {
  ['#fDateFrom', '#fDateTo', '#fMonth', '#fYear', '#fRM', '#fROM', '#fSD'].forEach(s => $(s).value = '');
  $('#fSearch').value = '';
  applyFilters();
}

/* ---------------------------------------------------------------------- *
 * 5. AGGREGATIONS
 * ---------------------------------------------------------------------- */
function aggregateBy(records, keyFn, masterCountFn) {
  const groups = groupBy(records, keyFn);
  const out = [];
  groups.forEach((items, key) => {
    const stores = new Set(items.map(i => i.storeCode));
    const gcs = items.map(i => i.gc);
    const total = gcs.reduce((a, b) => a + b, 0);
    const avg = gcs.length ? total / gcs.length : 0;
    const highest = gcs.length ? Math.max(...gcs) : 0;
    const lowest = gcs.length ? Math.min(...gcs) : 0;
    const netQtyDiff = items.reduce((a, i) => a + (i.netQtyDiff || 0), 0);
    const netValueDiff = items.reduce((a, i) => a + (i.netValueDiff || 0), 0);
    const masterTotal = masterCountFn ? masterCountFn(key) : stores.size;
    const completion = masterTotal ? (stores.size / masterTotal) * 100 : 0;
    out.push({ key, stores: stores.size, masterTotal, total, avg, highest, lowest, netQtyDiff, netValueDiff, completion });
  });
  return out.sort((a, b) => b.total - a.total);
}

function masterStoresFor(field, value) {
  return APP.storeMaster.filter(m => (m[field] || 'Unassigned') === value).length;
}

/* ---------------------------------------------------------------------- *
 * 6. RENDER: KPIs
 * ---------------------------------------------------------------------- */
function renderKPIs() {
  const rec = APP.filtered;
  const totalGC = rec.reduce((a, r) => a + r.gc, 0);
  const totalStoresMaster = APP.storeMaster.length || new Set(APP.records.map(r => r.storeCode)).size;
  const storesUploaded = new Set(rec.map(r => r.storeCode)).size;
  const rmCount = new Set(APP.storeMaster.map(m => m.rm)).size || new Set(rec.map(r => r.rm)).size;
  const romCount = new Set(APP.storeMaster.map(m => m.rom)).size || new Set(rec.map(r => r.rom)).size;
  const sdCount = new Set(APP.storeMaster.map(m => m.sd)).size || new Set(rec.map(r => r.sd)).size;
  const gcs = rec.map(r => r.gc);
  const avgGC = gcs.length ? totalGC / gcs.length : 0;
  const completion = totalStoresMaster ? (storesUploaded / totalStoresMaster) * 100 : 0;
  const missedCount = getMissedStores().length;

  const cards = [
    { label: 'Total Global Count', value: totalGC, icon: '🌍', gold: false },
    { label: 'Total Stores', value: totalStoresMaster, icon: '🏬', gold: false },
    { label: 'Stores Uploaded', value: storesUploaded, icon: '📤', gold: false },
    { label: 'RM Count', value: rmCount, icon: '🧑‍💼', gold: true },
    { label: 'ROM Count', value: romCount, icon: '🧑‍💻', gold: true },
    { label: 'SD Count', value: sdCount, icon: '🧑‍🔧', gold: true },
    { label: 'Average Global Count', value: avgGC, icon: '📐', gold: false, decimal: true },
    { label: 'GC Missed Stores', value: missedCount, icon: '🚫', gold: false },
    { label: 'Completion %', value: completion, icon: '✅', gold: true, suffix: '%', decimal: false },
  ];

  const grid = $('#kpiGrid');
  grid.innerHTML = cards.map((c, i) => `
    <div class="kpi-card ${c.gold ? 'gold' : ''}">
      <div class="kpi-top">
        <span class="kpi-label">${c.label}</span>
        <span class="kpi-icon">${c.icon}</span>
      </div>
      <div class="kpi-value counter" id="kpi-${i}">0</div>
    </div>`).join('');

  cards.forEach((c, i) => animateCounter($('#kpi-' + i), c.value, !!c.decimal, c.suffix || ''));
}

/* ---------------------------------------------------------------------- *
 * 7. RENDER: RM / ROM / SD TABLES
 * ---------------------------------------------------------------------- */
function renderRM() {
  const agg = aggregateBy(APP.filtered, r => r.rm, key => masterStoresFor('rm', key));
  renderGroupTable('#rmTable tbody', agg);
}

function renderROM() {
  const agg = aggregateBy(APP.filtered, r => r.rom, key => masterStoresFor('rom', key));
  renderGroupTable('#romTable tbody', agg);
}

function renderSD() {
  // An SD name that is also a known ROM name means that person is acting as
  // the ROM for that store, not a genuine SD — exclude those from the SD
  // summary so ROM names don't repeat/duplicate here.
  const romNames = new Set(APP.storeMaster.map(m => m.rom));
  const agg = aggregateBy(APP.filtered, r => r.sd, key => masterStoresFor('sd', key))
    .filter(a => !romNames.has(a.key));
  renderGroupTable('#sdTable tbody', agg);
}

function renderGroupTable(sel, agg) {
  const tbody = $(sel);
  tbody.innerHTML = agg.map((a) => `
    <tr>
      <td><strong>${a.key}</strong></td>
      <td>${fmtNum(a.masterTotal)}</td>
      <td>${fmtNum(a.stores)}</td>
      <td>${completionBadge(a.completion)}</td>
      <td>${fmtNum(a.netQtyDiff)}</td>
      <td>${fmtNum(a.netValueDiff)}</td>
    </tr>`).join('') || '<tr><td colspan="6" class="text-muted" style="text-align:center;padding:20px;">No data for selected filters</td></tr>';
}

function completionBadge(pct) {
  const cls = pct >= 90 ? 'success' : pct >= 60 ? 'warning' : 'danger';
  return `<span class="badge ${cls}">${fmtPct(pct)}</span>`;
}

/* ---------------------------------------------------------------------- *
 * 8. RENDER: DATE WISE COMPLETION SUMMARY
 * ---------------------------------------------------------------------- */
function renderDateSummary() {
  const totalStoresMaster = APP.storeMaster.length || new Set(APP.records.map(r => r.storeCode)).size;
  const agg = aggregateBy(APP.filtered, r => r.dateStr, () => totalStoresMaster)
    .filter(a => a.key && a.key !== 'Unassigned')
    .sort((a, b) => a.key.localeCompare(b.key));

  const tbody = $('#dateSummaryTable tbody');
  tbody.innerHTML = agg.map(a => `
    <tr>
      <td><strong>${fmtDate(a.key)}</strong></td>
      <td>${fmtNum(a.masterTotal)}</td>
      <td>${fmtNum(a.stores)}</td>
      <td>${completionBadge(a.completion)}</td>
    </tr>`).join('') || '<tr><td colspan="4" class="text-muted" style="text-align:center;padding:20px;">No data for selected filters</td></tr>';
}

/* ---------------------------------------------------------------------- *
 * 9. RENDER: GC MISSED STORES
 * A store counts as "missed" for the current filter scope when it belongs
 * to the selected RM/ROM/SD (if any) but has zero matching Global Count
 * records among APP.filtered — i.e. within whatever Date/Month/FY/RM/ROM/SD
 * filters are currently applied. This lets the same filter bar answer
 * "who hasn't done GC yet" for any single date, a date range, or a whole
 * RM/ROM/SD, without a separate set of controls.
 * ---------------------------------------------------------------------- */
function getMissedStores() {
  const f = getFilterState();
  const search = (f.search || '').toLowerCase();

  const scoped = APP.storeMaster.filter(m =>
    (!f.rm || m.rm === f.rm) &&
    (!f.rom || m.rom === f.rom) &&
    (!f.sd || m.sd === f.sd) &&
    (!search || `${m.code} ${m.name}`.toLowerCase().includes(search))
  );

  const presentCodes = new Set(APP.filtered.map(r => r.storeCode));
  return scoped.filter(m => !presentCodes.has(m.code));
}

function renderMissedStores() {
  const missed = getMissedStores().sort((a, b) => a.code.localeCompare(b.code));
  const tbody = $('#missedTable tbody');
  tbody.innerHTML = missed.map(m => `
    <tr>
      <td>${m.code}</td>
      <td><strong>${m.name}</strong></td>
      <td>${m.rm || 'Unassigned'}</td>
      <td>${m.rom || 'Unassigned'}</td>
      <td>${m.sd || 'Unassigned'}</td>
    </tr>`).join('') || '<tr><td colspan="5" class="text-muted" style="text-align:center;padding:20px;">No missed stores for the selected filters 🎉</td></tr>';

  const countEl = $('#missedCount');
  if (countEl) countEl.textContent = `${missed.length} store${missed.length === 1 ? '' : 's'}`;
}

/* ---------------------------------------------------------------------- *
 * 10. RENDER: STORE WISE GC (as per Excel format — one row per count entry)
 * ---------------------------------------------------------------------- */
function renderStoreWiseGC() {
  const term = ($('#storeSearchInput')?.value || '').toLowerCase();
  let list = APP.filtered.filter(r => !term || `${r.storeCode} ${r.storeName} ${r.doneBy} ${r.validatedBy} ${r.reason}`.toLowerCase().includes(term));

  list = [...list].sort((a, b) => {
    const dir = APP.storeSort.dir === 'asc' ? 1 : -1;
    const k = APP.storeSort.key;
    let va = k === 'date' ? (a.date ? a.date.getTime() : 0) : a[k];
    let vb = k === 'date' ? (b.date ? b.date.getTime() : 0) : b[k];
    if (typeof va === 'string') return va.localeCompare(vb) * dir;
    return ((va || 0) - (vb || 0)) * dir;
  });

  const totalPages = Math.max(1, Math.ceil(list.length / APP.storePageSize));
  APP.storePage = Math.min(APP.storePage, totalPages);
  const start = (APP.storePage - 1) * APP.storePageSize;
  const pageItems = list.slice(start, start + APP.storePageSize);

  $('#storeTable tbody').innerHTML = pageItems.map(r => `
    <tr>
      <td>${r.storeCode}</td>
      <td><strong>${r.storeName}</strong></td>
      <td>${fmtDate(r.date)}</td>
      <td><strong>${fmtNum(r.gc)}</strong></td>
      <td>${fmtNum(r.shortageQty)}</td>
      <td>${fmtNum(r.shortageMapValue, 2)}</td>
      <td>${fmtNum(r.excessQty)}</td>
      <td>${fmtNum(r.excessMapValue, 2)}</td>
      <td>${fmtNum(r.netQtyDiff)}</td>
      <td>${fmtNum(r.netValueDiff)}</td>
      <td>${r.doneBy || ''}</td>
      <td>${r.validatedBy || ''}</td>
      <td>${r.movedTo2997 || ''}</td>
      <td>${r.reason || ''}</td>
    </tr>`).join('') || '<tr><td colspan="14" style="text-align:center;padding:20px;" class="text-muted">No records match filters</td></tr>';

  renderPagination('#storePagination', APP.storePage, totalPages, (p) => { APP.storePage = p; renderStoreWiseGC(); });

  APP.storeExportData = list;
}

function renderPagination(sel, current, total, onPage) {
  const el = $(sel);
  let html = '';
  html += `<button ${current === 1 ? 'disabled' : ''} data-p="${current - 1}">‹ Prev</button>`;
  const span = 2;
  for (let p = 1; p <= total; p++) {
    if (p === 1 || p === total || (p >= current - span && p <= current + span)) {
      html += `<button class="${p === current ? 'active' : ''}" data-p="${p}">${p}</button>`;
    } else if (p === current - span - 1 || p === current + span + 1) {
      html += `<span style="padding:0 4px;">…</span>`;
    }
  }
  html += `<button ${current === total ? 'disabled' : ''} data-p="${current + 1}">Next ›</button>`;
  el.innerHTML = html;
  $all('button[data-p]', el).forEach(btn => btn.addEventListener('click', () => onPage(Number(btn.dataset.p))));
}

/* ---------------------------------------------------------------------- *
 * 11. RENDER: RAW DATA (fully dynamic columns/rows)
 * ---------------------------------------------------------------------- */
function renderRawHead() {
  const headRow = $('#rawDataHeadRow');
  headRow.innerHTML = APP.columns.map((c, i) => `<th data-col="${i}">${c} <span class="sort-ind">⇅</span></th>`).join('');
  $all('#rawDataHeadRow th').forEach(th => th.addEventListener('click', () => {
    const col = Number(th.dataset.col);
    if (APP.rawSort.key === col) APP.rawSort.dir = APP.rawSort.dir === 'asc' ? 'desc' : 'asc';
    else { APP.rawSort.key = col; APP.rawSort.dir = 'asc'; }
    renderRaw();
  }));
}

function renderRaw() {
  const search = ($('#rawSearchInput').value || '').toLowerCase();
  let rows = APP.rows.map((r, i) => ({ r, i }));
  if (search) rows = rows.filter(({ r }) => r.some(cell => String(cell ?? '').toLowerCase().includes(search)));
  if (APP.rawSort.key !== null) {
    rows.sort((a, b) => {
      const va = a.r[APP.rawSort.key], vb = b.r[APP.rawSort.key];
      const dir = APP.rawSort.dir === 'asc' ? 1 : -1;
      if (typeof va === 'number' && typeof vb === 'number') return (va - vb) * dir;
      return String(va ?? '').localeCompare(String(vb ?? '')) * dir;
    });
  }
  APP.rawFilteredRows = rows.map(x => x.r);

  const totalPages = Math.max(1, Math.ceil(rows.length / APP.rawPageSize));
  APP.rawPage = Math.min(APP.rawPage, totalPages);
  const start = (APP.rawPage - 1) * APP.rawPageSize;
  const pageRows = rows.slice(start, start + APP.rawPageSize);

  $('#rawDataTable tbody').innerHTML = pageRows.map(({ r }) => `<tr>${r.map(cell => `<td>${formatRawCell(cell)}</td>`).join('')}</tr>`).join('')
    || `<tr><td colspan="${APP.columns.length}" style="text-align:center;padding:20px;" class="text-muted">No matching rows</td></tr>`;

  renderPagination('#rawDataPagination', APP.rawPage, totalPages, (p) => { APP.rawPage = p; renderRaw(); });
}

function formatRawCell(cell) {
  if (cell === null || cell === undefined || cell === '') return '';
  return String(cell);
}

/* ---------------------------------------------------------------------- *
 * 12. RENDER ALL
 * ---------------------------------------------------------------------- */
function renderAll() {
  renderKPIs();
  renderRM();
  renderROM();
  renderSD();
  renderDateSummary();
  renderMissedStores();
  renderStoreWiseGC();
  renderRaw();
}

/* ---------------------------------------------------------------------- *
 * 13. EXPORTS
 * ---------------------------------------------------------------------- */
function exportRawExcel() {
  const ws = XLSX.utils.aoa_to_sheet([APP.columns, ...APP.rawFilteredRows]);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Raw Data');
  XLSX.writeFile(wb, `Hamleys_GC_RawData_${Date.now()}.xlsx`);
}

function exportRawCsv() {
  const lines = [APP.columns, ...APP.rawFilteredRows].map(row => row.map(v => `"${String(v ?? '').replace(/"/g, '""')}"`).join(','));
  downloadFile(`Hamleys_GC_RawData_${Date.now()}.csv`, lines.join('\n'), 'text/csv');
}

function exportStoreExcel() {
  const data = (APP.storeExportData || []).map(r => ({
    'Store Code': r.storeCode,
    'Store Name': r.storeName,
    Date: fmtDate(r.date),
    "No. of SKU's Counted": r.gc,
    'Shortage Qty': r.shortageQty,
    'Shortage MAP Value': r.shortageMapValue,
    'Excess Qty': r.excessQty,
    'Excess MAP Value': r.excessMapValue,
    'Total Net Qty Difference': r.netQtyDiff,
    'Total Net MAP Value Difference': r.netValueDiff,
    'Global Count Done by': r.doneBy,
    'Global Count Validated by': r.validatedBy,
    'Shortage Qty Moved to 2997 ?': r.movedTo2997,
    'Reason for Short or Excess Qty': r.reason,
  }));
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Store wise GC');
  XLSX.writeFile(wb, `Hamleys_GC_StoreWiseGC_${Date.now()}.xlsx`);
}

/* ---------------------------------------------------------------------- *
 * 14. THEME / TABS / EVENTS
 * ---------------------------------------------------------------------- */
function initTheme() {
  const saved = localStorage.getItem('hamleys-gc-theme') || 'light';
  document.documentElement.setAttribute('data-theme', saved);
  $('#themeToggle').textContent = saved === 'dark' ? '☀️' : '🌙';
  $('#themeToggle').addEventListener('click', () => {
    const cur = document.documentElement.getAttribute('data-theme');
    const next = cur === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('hamleys-gc-theme', next);
    $('#themeToggle').textContent = next === 'dark' ? '☀️' : '🌙';
  });
}

function initTabs() {
  $all('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      $all('.tab-btn').forEach(b => b.classList.remove('active'));
      $all('.tab-panel').forEach(p => p.classList.remove('active'));
      btn.classList.add('active');
      $('#tab-' + btn.dataset.tab).classList.add('active');
    });
  });
}

function initEvents() {
  ['#fDateFrom', '#fDateTo', '#fMonth', '#fYear', '#fRM', '#fROM', '#fSD'].forEach(s => $(s).addEventListener('change', applyFilters));
  $('#fSearch').addEventListener('input', debounce(applyFilters, 250));
  $('#resetFiltersBtn').addEventListener('click', resetFilters);
  $('#refreshBtn').addEventListener('click', async () => {
    $('#refreshBtn').innerHTML = '<span class="spinner small"></span> Refreshing';
    await loadData(true);
    $('#refreshBtn').innerHTML = '⟳ Refresh';
  });

  $('#storeSearchInput').addEventListener('input', debounce(() => { APP.storePage = 1; renderStoreWiseGC(); }, 250));
  $('#storeExportBtn').addEventListener('click', exportStoreExcel);

  $('#rawSearchInput').addEventListener('input', debounce(() => { APP.rawPage = 1; renderRaw(); }, 250));
  $('#rawExportExcelBtn').addEventListener('click', exportRawExcel);
  $('#rawExportCsvBtn').addEventListener('click', exportRawCsv);
  $('#rawPrintBtn').addEventListener('click', () => window.print());
}

function initSortableHeaders() {
  $all('#storeTable thead th').forEach(th => {
    th.addEventListener('click', () => {
      const key = th.dataset.key;
      if (APP.storeSort.key === key) APP.storeSort.dir = APP.storeSort.dir === 'asc' ? 'desc' : 'asc';
      else { APP.storeSort.key = key; APP.storeSort.dir = 'desc'; }
      renderStoreWiseGC();
    });
  });
}

/* ---------------------------------------------------------------------- *
 * 15. INIT
 * ---------------------------------------------------------------------- */
document.addEventListener('DOMContentLoaded', async () => {
  initTheme();
  initTabs();
  renderRawHead();
  initEvents();
  initSortableHeaders();

  try {
    await loadData(false);
  } catch (err) {
    console.error(err);
    $('#kpiGrid').innerHTML = `<div class="alert error" style="grid-column:1/-1;">⚠️ ${err.message}. Please generate data via the Admin page first.</div>`;
  } finally {
    setTimeout(() => $('#loaderOverlay').classList.add('hidden'), 400);
  }

  // Auto-refresh every 5 minutes (silent)
  setInterval(() => loadData(true).catch(() => {}), 5 * 60 * 1000);
});
